namespace EquipmentBorrowing.Domain;

/// <summary>
/// Represents a single borrowing transaction: one student borrowing one
/// piece of equipment for a period of time.
/// </summary>
/// <remarks>
/// <para><b>Responsibility:</b> records who borrowed what, when, and until
/// when, and tracks whether that specific loan is still active or has been
/// returned.</para>
/// <para>
/// <see cref="StudentId"/> and <see cref="EquipmentId"/> are stored as plain
/// identifiers rather than direct references to <see cref="Student"/> and
/// <see cref="Equipment"/> objects. This keeps the model simple to persist
/// later (e.g. as foreign keys in a database table) and avoids one entity
/// having to hold a live, mutable reference to another.
/// </para>
/// <para>
/// <see cref="Id"/> is a <see cref="Guid"/> generated by the entity itself
/// at creation time, rather than an auto-increment integer. Unlike
/// <see cref="Student"/> and <see cref="Equipment"/> — which represent
/// existing catalog data that a future database would assign integer keys
/// to — a <c>Borrowing</c> is created fresh at runtime by the application,
/// so it can safely generate its own unique identity without needing a
/// database round-trip first.
/// </para>
/// <para><b>Not this class's responsibility:</b> deciding whether the
/// student was allowed to borrow, or whether the equipment was available.
/// Those checks depend on other objects and must happen before a
/// <c>Borrowing</c> is created — that coordination belongs to the
/// Application layer.</para>
/// </remarks>
public class Borrowing
{
    public Guid Id { get; }
    public int StudentId { get; }
    public int EquipmentId { get; }
    public DateOnly DateBorrowed { get; }
    public DateOnly ExpectedReturnDate { get; }
    public BorrowingStatus Status { get; private set; }

    public Borrowing(int studentId, int equipmentId, DateOnly dateBorrowed, DateOnly expectedReturnDate)
    {
        if (expectedReturnDate < dateBorrowed)
        {
            throw new ArgumentException(
                "Expected return date cannot be before the borrow date.",
                nameof(expectedReturnDate));
        }

        Id = Guid.NewGuid();
        StudentId = studentId;
        EquipmentId = equipmentId;
        DateBorrowed = dateBorrowed;
        ExpectedReturnDate = expectedReturnDate;
        Status = BorrowingStatus.Active;
    }

    public void MarkAsReturned()
    {
        if (Status == BorrowingStatus.Returned)
        {
            throw new InvalidOperationException("This borrowing has already been returned.");
        }

        Status = BorrowingStatus.Returned;
    }
}
